FROM gocd/gocd-agent-ubuntu-18.04:v20.1.0

USER root
RUN curl -L --fail https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl --output /usr/local/bin/kubectl && \
  chmod +x /usr/local/bin/kubectl
USER go
